{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flink-operator.serviceAccountName" . }}
  labels:
{{ include "flink-operator.labels" . | indent 4 }}
{{- end -}}
