apiVersion: apps/v1
kind: Deployment
metadata:
  name: beam-job-server
spec:
  selector:
    matchLabels:
      app: beam-job-server
  replicas: 1
  template:
    metadata:
      labels:
        app: beam-job-server
    spec:
      containers:
        - name: beam-job-server
          image: apache/beam_flink1.8_job_server:2.22.0
          imagePullPolicy: Always
          args:
            - "--flink-master=beam-flink-cluster-jobmanager:8081"
            - "--artifacts-dir=gs://tfx-ccy-test-1/flink-test"
---
apiVersion: v1
kind: Service
metadata:
  name: beam-job-server
spec:
  ports:
    - name: job
      port: 8099
      targetPort: 8099
    - name: artifact
      port: 8098
      targetPort: 8098
  selector:
    app: beam-job-server
