# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: wordcount
spec:
  image:
    name: flink:1.9.2
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  job:
    jarFile: /cache/flink-app.jar
    className: org.apache.flink.streaming.examples.wordcount.WordCount
    args: ["--input", "./README.txt"]
    parallelism: 1
    savepointsDir: /cache/savepoints
    initContainers:
      - name: downloader
        image: curlimages/curl
        env:
          - name: JAR_URL
            value: https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.9.2/flink-examples-streaming_2.12-1.9.2-WordCount.jar
          - name: DEST_PATH
            value: /cache/flink-app.jar
        command: ['sh', '-c', 'curl -o ${DEST_PATH} ${JAR_URL}']
    volumes:
      - name: cache
        emptyDir: {}
    volumeMounts:
      - mountPath: /cache
        name: cache
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
