apiVersion: batch/v1
kind: Job
metadata:
  name: beam-wordcount-py-5
spec:
  template:
    metadata:
      labels:
        app: beam-wordcount-py
    spec:
      containers:
        - name: beam-wordcount-py
          image: apache/beam_python3.7_sdk:2.22.0
          command: ["python3"]
          args:
            - "-m"
            - "apache_beam.examples.wordcount"
            - "--runner=FlinkRunner"
            - "--flink_master=beam-flink-cluster-jobmanager:8081"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
            - "--input"
            - "/etc/ucf.conf"
            - "--output"
            - "gs://tfx-ccy-test-1/tmp/blah"
      restartPolicy: Never
