name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/spotify/flink-operator:${GITHUB_SHA::8}
          echo ::set-output name=image::${DOCKER_IMAGE}
      - name: Login to Github container registry
        uses: docker/login-action@v1.1.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push image
        run: make operator-image push-operator-image
        env:
          IMG: ${{ steps.prep.outputs.image }}
